persist_directory: "/root/autodl-tmp/database/chroma"
embeddings_model_name: "intfloat/multilingual-e5-large"
llm: "qwen2:72b"
ollama_base_url: "http://127.0.0.1:11434"
all_data: "./data/final_data/lotus"
car_stats: "./data/final_data/lotus_car_stats"
brand_info: "./data/final_data/lotus_brand_info"