file_path: "/root/autodl-tmp/RAG_Agent/data/final_data/"
persist_directory: "/root/autodl-tmp/database/chroma"
embeddings_model_name: "intfloat/multilingual-e5-large"
llm: "qwen2:72b"
sllm: "qwen2:72b"
ollama_base_url: "http://127.0.0.1:11434"